### ISSUE TITLE
AttributeError: module 'fingerprint' has no attribute 'DEFAULT_FS'

### ISSUE THREAD

**Issue by war21x3b** [kailashbuki/fingerprint#10]
Hi, I ran into a problem when importing a module. I use python 3. Please tell me how to solve my problem. Thanks!

![image](https://github.com/kailashbuki/fingerprint/assets/32517357/393230c3-4bf3-4968-861c-282be6256735)

**Comment by kailashbuki** [comment]
Unrelated to this package.
