### ISSUE TITLE
Lots of selected hashes are 0

### ISSUE THREAD

**Issue by vimanyuawal** [kailashbuki/fingerprint#5]
Hi,

I was looking at your implementation of winnowing and decided to try it out on a project I am working on. I have .txt files that I am using this on to create digital fingerprints for these files. With the kgram length as 5 and a window length of 19 (therefore expected keys selected should be close to 2/(1+window length) = 10%), I am getting around 50% of my hashes as fingerprints. Out of this 50%, around 85% have a value of 0 in different positions. Do you have any idea why this could be the case?

**Comment by kailashbuki** [comment]
Can you share the txt file, or a similar one to reproduce the error?

**Comment by vimanyuawal** [comment]
Nevermind, the issue was on my own end. I had a lot of '\x00\x00\x00\x00\x00', which I need to remove beforehand. Thank you anyway!
