### ISSUE TITLE
Winnowing not recognizing copies

### ISSUE THREAD

**Issue by vimanyuawal** [kailashbuki/fingerprint#6]
Hi,

I was using your algorithm to classify different documents and while it was working well, for some reason when I apply OCR to handwritten forms (text is valid I have checked) somehow none of the hashed fingerprints match another similar form. I have attached the two forms I am comparing along with this issue. Any help on this is appreciated!

These are IRS forms (1099) and I have filled one with random data on a page and the other one is just a template. I want to see if there is a similarity in their fingerprints (which there should be), but it shows no common fingerprints.

[f1099msc.txt](https://github.com/kailashbuki/fingerprint/files/4865771/f1099msc.txt)
[1099_2.txt](https://github.com/kailashbuki/fingerprint/files/4865772/1099_2.txt)

**Comment by kailashbuki** [comment]
What parameters do you provide when creating the object of `Fingerprint` class?
```python
fprint = fingerprint.Fingerprint(kgram_len=4, window_len=5, base=10, modulo=1000)
```
The generated fingerprints depend on the length of kgrams (`kgram_len`) and window length (`window_len`). 
Try increasing them to a larger value. In the example presented at the front page of this package, we have a string of small length. That is why those parameters are small. You can also resort to default parameters with this:
```python
fprint = fingerprint.Fingerprint()
```

**Comment by vimanyuawal** [comment]
Yes, I understand that. I have tried with the default values and even set them as low as 1 for kgram length and 2 for window length to maximize the number of fingerprints stored for each document. I have even modified the code to do winnowing without taking into account the position (by simply setting the positional part of the tuple as 0). I store the fingerprints of both the documents attached as sets and find their intersection but there is nothing in common. I don't understand how this is possible?

**Comment by kailashbuki** [comment]
https://colab.research.google.com/drive/1N8VRtwPKkow6S0y9zda_PMt6ggswIUdD?usp=sharing

You can also replace the hashing algorithm with an algorithm of your choice by the way.

**Comment by vimanyuawal** [comment]
Thank you so much for writing that code out and showing that as proof :)

Yes it seems like your algorithm works perfectly and there is some error in my own code. I really appreciate you taking out the time to solve this and writing out that example!
